vich_uploader:
    db_driver: orm

    mappings:
        Custom_image:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
#            delete_on_remove: false
