vich_uploader:
    db_driver: orm

    mappings:
        Clients_image:
            uri_prefix: /uploads/images/clients
            upload_destination: '%kernel.project_dir%/public/uploads/images/clients'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true

        Slider_image:
            uri_prefix: /uploads/images/slider
            upload_destination: '%kernel.project_dir%/public/uploads/images/slider'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true

        Bloc_image:
            uri_prefix: /uploads/images/bloc
            upload_destination: '%kernel.project_dir%/public/uploads/images/bloc'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
#            delete_on_remove: false
