#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home_shortcut:
  path:
    home: /
    entreprise: /site/entreprise.html
    clients: /site/ils-nous-font-confiance.html?Name=Value
    localisation: /site/situation-geographique.html
    contact: /site/contact.html
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: "home"
    _locale: fr
