#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home_shortcut:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: "home"
    _locale: fr
